# Generated by Django 4.0.6 on 2022-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commid', models.CharField(db_column='commID', max_length=20, primary_key=True, serialize=False)),
                ('reply', models.TextField(blank=True, null=True)),
                ('replylikes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('idx', models.IntegerField()),
                ('placeid', models.CharField(db_column='placeID', max_length=12, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=20)),
                ('paddress', models.CharField(max_length=50)),
                ('pdo', models.CharField(blank=True, max_length=10, null=True)),
                ('psi', models.CharField(blank=True, max_length=15, null=True)),
                ('pphone', models.CharField(blank=True, max_length=13, null=True)),
                ('pdaumurl', models.CharField(blank=True, db_column='pdaumURL', max_length=30, null=True)),
                ('px', models.FloatField(db_column='pX')),
                ('py', models.FloatField(db_column='pY')),
            ],
            options={
                'db_table': 'places',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('videoid', models.CharField(db_column='videoID', max_length=11, primary_key=True, serialize=False)),
                ('channelname', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=48, null=True)),
                ('youtime', models.DateField()),
                ('views', models.IntegerField(blank=True, null=True)),
                ('youtlikes', models.IntegerField(blank=True, null=True)),
                ('lencomments', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'youtube',
                'managed': False,
            },
        ),
    ]
